apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Pull Request Action template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the component
        targetPath:
          title: Target Path in repo
          type: string
          description: Name of the directory to create in the repository
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - dev.azure.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{parameters.name}}

    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions

    - id: debug-github-condition
      name: Debug GitHub Condition
      action: debug:log
      input:
        message: 'GitHub Condition: ${{ parameters.repoUrl.includes(''github.com'') }}'

    - id: publish-github
      name: Publish to GitHub
      action: publish:github:pull-request
      if: ${{ parameters.repoUrl.includes('github.com') }}
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new project: ${{parameters.name}}"
        branchName: create-${{parameters.name}}
        description: |
          # New project: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.name }}

    - id: debug-azure-condition
      name: Debug Azure Condition
      action: debug:log
      input:
        message: 'Azure Condition: ${{ parameters.repoUrl.includes(''dev.azure.com'') }}'

    - id: publish-azure
      name: Publish to Azure
      action: publish:azure:pull-request
      if: ${{ parameters.repoUrl.includes('dev.azure.com') }}
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new project: ${{parameters.name}}"
        branchName: create-${{parameters.name}}
        description: |
          # New project: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.name }}

  output:
    links:
      - url: ${{ steps['publish-github'].output.remoteUrl or steps['publish-azure'].output.remoteUrl }}
        title: "Go to PR"
